Viite-2597 fix continuity code on change table
finnishtransportagency/viite pull request #1075
Opened 2021-09-07 07:24 UTC by ao-sitowise

Tests ok.

2021-09-07 12:38 UTC, LauriLitmanenSW commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
> +      val ra = Seq(
Miksi "ra" eikä esimerkiksi "roadway" tai "rw". "ra" tulee mieleen roadAddress

2021-09-07 12:40 UTC, LauriLitmanenSW commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
> +      val dao = new RoadwayChangesDAO()
roadwayChangesDAO olisi selkeämpi nimeäminen

2021-09-07 12:48 UTC, LauriLitmanenSW commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
> +    val newProjectLink4 = ProjectLink(4, 1, 1, Track.Combined, Discontinuity.Discontinuous, 30, 40, 30, 40, None, None, Some("test"), 0, 0.0, 0.0, SideCode.Unknown, (NoCP, NoCP), (NoCP, NoCP), List()
newProjectLink saa sellaisen kuvan että toimenpide on "uusi", pelkkä projectLink(n) olisi ehkä parempi

2021-09-08 05:52 UTC, LauriLitmanenSW commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
> +        Roadway(0, 1111, newProjectLink4.roadNumber, newProjectLink4.roadPartNumber, AdministrativeClass.Municipality, Track.Combined, Discontinuity.Discontinuous, 0, 40, reversed = false, DateTime.p
startDate tarkoituksella 2120?

2021-09-08 05:54 UTC, LauriLitmanenSW commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
> +    val newProjectLink1 = ProjectLink(1, 1, 1, Track.Combined, Discontinuity.Continuous, 0, 10, 0, 10, None, None, Some("test"), 0, 0.0, 0.0, SideCode.Unknown, (NoCP, NoCP), (NoCP, NoCP), List(), 1,
pelkkä hallinnollisen luokan muutos kuuluisi ilmeisesti tehdä Ennallaan -toimenpiteellä

2021-09-08 09:49 UTC, marjukka-kokkonen-sitowise requested changes

2021-09-08 09:49 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
> +  def originalDiscontinuity = if (isTheLastProjectLinkOnRoadway) roadway.get.discontinuity else if (roadway.isDefined) Discontinuity.Continuous else discontinuity
originalDiscontinuity ei lähtökohtaisesti kuulosta siltä, että sillä pitäisi olla monta erilaista mahdollista arvoa (joo, vaikka se on lähinnä kai "lähtötieto", mutta silti.) -> tähän aukiparsintaselitys, miksi eri vaihtoehdot, please

2021-09-08 09:49 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
> +    val isContinuous = pl1.discontinuity == Discontinuity.Continuous
Jes, parempi nimi 👍

2021-09-08 09:49 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
> +        matchAdministrativeClass) {
(No kun tätä muuttujaa nyt käpistellään ... p.o. administrativeClassesMatch?)

2021-09-08 09:49 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
> +  def addProject(): Unit = {
addAutomatedTestProject tai addDummyprojectForTests tai jotain.
Nyt turhan geneerinen nimi; tämän ei liene tarkoitus olla kovin yleiskäyttöinen

2021-09-08 11:52 UTC, LauriLitmanenSW approved these changes

2021-09-08 11:53 UTC, LauriLitmanenSW approved these changes

2021-09-09 06:26 UTC, merged