Viite 2630 - Wrong continuity code on changetable source
finnishtransportagency/viite pull request #1082
Opened 2021-09-16 11:12 UTC by ao-sitowise

2021-09-16 12:45 UTC, AnttiJokela approved these changes

2021-09-17 04:23 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala
> +      /* A road of length 120 is split from 60 to two parts and discontinuity is changed. */
👍 Aukipurku on pop!

2021-09-17 05:30 UTC, marjukka-kokkonen-sitowise requested changes
Testi: Kauniimminnätimminparemminnimettynä!
Kestää hirmu kauan tsekata, ovatko varsinaiset testirivit sisällöltään järkeviä, kun matkalla lukijan pään muistipaikoista häviää tieto tsekattavien asioiden sisällöistä, eivätkä geneeriset partition-n-head -nimet tue sisällön ymmärtämistä.
Ja sit tietysti noita iänikuisia kosmeettisuuksia. :)

2021-09-17 05:30 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala
> +        par._1.roadPartNumberStart == 205 && par._2.roadPartNumberStart == 205
(Voi olla, että kyselen vaihteeks tyhmiä, mutta) Mistä tää 205 tulee, löydän tästä testistä vain 206:a?

2021-09-17 05:30 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala
> +      val (to1, fr1) = partitions3._1.head
"to"? "fr"?

Tähän mennessä multa myös jo ehtii kadota käsitys siitä, mitä partitions2._1.head, ja alemman blokin partitions2._2.head sisältävät. -> BLokeille vielä kommentit siitä, _minkä_ jatkuvuudet ja osoitteet näissä tsekataan. 
(Tai sitten nimiremppaa, eli kuvaavammat nimet partitionsX- ym. muuttujille s.e. kertovat eksplisiittisesti mitä sisältävät.)

2021-09-21 12:33 UTC, merged