Viite 2546
finnishtransportagency/viite pull request #1087
Opened 2021-09-20 09:47 UTC by ao-sitowise

Tests ok.

2021-09-20 11:19 UTC, LauriLitmanenSW commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
> +        val onceConnectedLinks         = TrackSectionOrder.findOnceConnectedLinks(remainLinks)
Onko tarkoituksella jätetty väli ennen yhtäkuin (=) merkkiä?

2021-09-20 11:29 UTC, LauriLitmanenSW approved these changes

2021-09-21 05:33 UTC, marjukka-kokkonen-sitowise requested changes
...menee taas niin syvälle substanssiin, etten harmikseni osaa kovin kummosiesti validoida itse ratkaisun tai testien järkevyyttä. :/

2021-09-21 05:33 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefaultSectionCalculatorStrategySpec.scala
> +  test("Test findStartingPoints " +
(rivitys <3
Näin näistä testien selosteista saa jonkun tolkun :) )

2021-09-21 05:33 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefaultSectionCalculatorStrategySpec.scala
> +      val geom1 = Seq(Point(372017, 6669721), Point(371826, 6669765))
kommentoitko tähän näiden ylle, tai ensimmäisen rivin loppuun:
// Point(371826, 6669765) found in three geometries

(Tai jos haluaa vielä selkeämmäksi, niin ton kyseisen Pointin vois napsia omaan muuttujaansa, ja sit vaan sijoitella noille riveille)

2021-09-21 05:33 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefaultSectionCalculatorStrategySpec.scala
> +      startingPointsForCalculations should be (geom1.last,geom1.last)
ja sit jos tuolla yllä se kolmipiste on napsittu omaksi muuttujakseen, sen voi antaa myös tähän, niin jälleen on selkeämpää, mitä verrataan mihin

2021-09-21 05:33 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala
> +      val geom1 = Seq(Point(372017, 6669721), Point(371826, 6669765))
(täällä samat kommentit kuin ylemmässä testissä; kommentti, tai Point erilliseen muuttujaan -> selkeyttää)

2021-09-21 05:33 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala
> +      // Check correct addresses have not changed.
(nillinnii:
Check _that_ correct --- )

2021-09-21 05:43 UTC, sasuolanderSito commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala
> +      val geom1 = Seq(Point(372017, 6669721), Point(371826, 6669765))
tai geom1 voi uudelleen nimetä, kaikki variable1,variable2,variable3 ... ovat huonoja muuttuja nimiä.

Mutta toisaalto jos alkaa olla liikaa muuttujia joiden ainoo tehtävä antaa joku nimi sille voi luettavuus myös kärsiä kun pomppoilee missä mikäkin on määritetty ja mitä arvoja annettu.

2021-09-21 07:13 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
> +          }).groupBy(_.x)
👍

2021-09-21 07:15 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefaultSectionCalculatorStrategySpec.scala
> +      val geom1 = Seq(Point(372017, 6669721), Point(371826, 6669765))
Teit molemmat :D <3

2021-09-21 07:18 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala
> +      val geom1 = Seq(Point(372017, 6669721), Point(371826, 6669765))
geomX on ihan hyviä nimiä tässä imo;  ne ovat nimenomaan juuri vain sitä; viivanpätkiä, joista osan on tarkoitus osua geometrisesti yhteen yhdestä päästä; ei niille sen parempia tartte, tai ehkä voi (tai joo, ole järkevää) keksiä.
Mutta toi piste, jonka on tarkoitus sit osua yhteen, on ymmärryksen kannalta oleellista osata bongata.

2021-09-21 07:19 UTC, marjukka-kokkonen-sitowise approved these changes

2021-09-21 09:26 UTC, LauriLitmanenSW commented
ASCII art tiestä vielä😁 👌

2021-09-21 13:17 UTC, marjukka-kokkonen-sitowise requested changes

2021-09-21 13:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
> +  def groupConnectionPoints(seq: Seq[ProjectLink]): Map[(Double, Double), Seq[Point]] = {
/** Group together points of the given ProjectLinks having the same (x,y) coordinates. */

2021-09-21 13:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
> +  def groupConnectionPoints(seq: Seq[ProjectLink]): Map[(Double, Double), Seq[Point]] = {
Jes, nyt on sen kokoisia funkkareita, että näistä pystyy saamaan tolkun! \o/

2021-09-24 06:43 UTC, merged