VIITE-2672 add aws prod deploy script
finnishtransportagency/viite pull request #1161
Opened 2022-01-24 09:40 UTC by LauriLitmanenSW

2022-02-01 11:10 UTC, marjukka-kokkonen-sitowise requested changes

2022-02-01 11:10 UTC, marjukka-kokkonen-sitowise commented on aws/aws-deploy-prod.sh
> +# Ask centralized service to update the service (notes on how to do that are in the readme)
Hei tää on hyvä kommentti...
Tän vois kirjoittaa (myös) echon sisään muistuttamaan devaajaa, et tarttee hihkua CS:n suuntaan.

2022-02-01 11:13 UTC, sasuolanderSito commented on aws/aws-deploy-prod.sh
> +# Ask centralized service to update the service (notes on how to do that are in the readme)
eikös tää kuuluis johonkin teidän pilvi dokumentaatioon confluensaa miten prosessi menee

2022-02-01 11:14 UTC, sasuolanderSito commented on aws/aws-deploy-prod.sh
> +# Ask centralized service to update the service (notes on how to do that are in the readme)
täältä tätä tuskin kauheen moni tulee katsomaan vaikka hyvä olla täälä myös

2022-02-01 11:17 UTC, LauriLitmanenSW commented on aws/aws-deploy-prod.sh
> +# Ask centralized service to update the service (notes on how to do that are in the readme)
> eikös tää kuuluis johonkin teidän pilvi dokumentaatioon confluensaa miten prosessi menee, onkos teillä sellaista jo
ei taida olla vielä, kaikki aikanaan 😄

2022-02-01 11:19 UTC, sasuolanderSito commented on aws/aws-deploy-prod.sh
> +# Ask centralized service to update the service (notes on how to do that are in the readme)
sitten viel diagrammi kuvaus perään Väylän mallin mukaisesti

2022-02-01 11:20 UTC, sasuolanderSito commented on aws/aws-deploy-prod.sh
> +# Ask centralized service to update the service (notes on how to do that are in the readme)
mut joo ei tässä varmaan mitään kiirettä ole

2022-02-01 11:24 UTC, LauriLitmanenSW commented on aws/aws-deploy-prod.sh
> +# Ask centralized service to update the service (notes on how to do that are in the readme)
Tääkin on tilapäinen tapa päivittää tuotannon kontti, Matti taisi puhua jostain aws codepipelinesta tms jolla se QA kontti sitten lähetetään centralized servicen prod repoon.

2022-02-07 08:46 UTC, ao-sitowise approved these changes

2022-02-07 08:58 UTC, merged