VIITE-2710
finnishtransportagency/viite pull request #1188
Opened 2022-03-30 12:10 UTC by ao-sitowise

Fixed existing address length changed in calculation.

2022-04-04 12:04 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
> +                                         startSectionAddress + rightProjectLinks.last.endAddrMValue - rightProjectLinks.head.startAddrMValue) * 0.5).round
"/2" would more explicitly refer to averaging, than "0.5".
-> use /2 instead of 0.5, if there are no logical reasons to use a decimal number

2022-04-04 12:04 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
> +                                         startSectionAddress + rightProjectLinks.last.endAddrMValue - rightProjectLinks.head.startAddrMValue) * 0.5).round
(...also, refactoring the averaging to a small function might be a good thing)

2022-04-06 05:44 UTC, LauriLitmanenSW requested changes
Marjukalta jälleen hyvät kommentit

2022-04-12 11:26 UTC, merged

2022-04-12 14:11 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
> +                                         startSectionAddress + rightProjectLinks.last.endAddrMValue - rightProjectLinks.head.startAddrMValue) * 0.5).round
Ha! Käytetty jo olemassa olevaa funktiota! Vielä parempi fiksi! <3
(Tosin, sielläkin näyttää käytetyn 0.5:sta. Noh... No niin. :D)