VIITE-2699
finnishtransportagency/viite pull request #1189
Opened 2022-03-31 11:06 UTC by ao-sitowise

Fixed saving to road network

2022-04-01 13:22 UTC, SitowiseValtteriV approved these changes

2022-04-04 09:58 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
> +       "Then roadways should be formed correctly.") {
"Then roadways should be formed correctly."
Aukipurku: mitä on "correctly" tässä?

2022-04-04 10:06 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
> +    test("Test defaultSectionCalculatorStrategy.updateRoadwaysAndLinearLocationsWithProjectLinks() " +
indentointi

2022-04-04 10:29 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
> +      val thirdRw = roadways.find(r => r.startAddrMValue == 369 && r.endAddrMValue == 1035)
Näihin lisäks r.track==(Left|Right)Side, niin on eksplisiittisempi, ja hahmottuu nopeammin?

2022-04-04 12:16 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
> +      val thirdRw = roadways.find(r => r.startAddrMValue == 369 && r.endAddrMValue == 1035)
Näihin lisäks r.track==(Left|Right)Side, niin on eksplisiittisempi, ja hahmottuu nopeammin?

2022-04-06 05:33 UTC, LauriLitmanenSW requested changes
Marjukalta hyvät kommentit

2022-04-11 07:22 UTC, LauriLitmanenSW commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
> +      val secondRw = roadways.find(_.endAddrMValue == 785 && r.track == Track.LeftSide)
puuttuuko tästä .find(r => )

2022-04-11 07:26 UTC, LauriLitmanenSW commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
> +      val secondRw = roadways.find(_.endAddrMValue == 785 && r.track == Track.LeftSide)
täällä puuttuu myös .find(r =>

2022-04-11 07:26 UTC, LauriLitmanenSW commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
> +      val firstRw = roadways.find(_.startAddrMValue == 0 && r.track == Track.Combined)
ja täällä

2022-04-11 07:48 UTC, LauriLitmanenSW approved these changes

2022-04-11 07:50 UTC, merged