VIITE-2696
finnishtransportagency/viite pull request #1192
Opened 2022-04-01 06:06 UTC by ao-sitowise

Fixed validation for splitted projectlinks.

2022-04-06 05:11 UTC, LauriLitmanenSW approved these changes

2022-04-08 06:44 UTC, marjukka-kokkonen-sitowise requested changes

2022-04-08 06:44 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
> +    val (allSplitted, nonSplitted) = (leftCombinedLinks ++ rightCombinedLinks).partition(_.isSplit)
^,v Näissä on niin paljon logiikkaa, että kaipaavat selitteen

2022-04-08 06:44 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
> +    val (allSplitted, nonSplitted) = (leftCombinedLinks ++ rightCombinedLinks).partition(_.isSplit)
^,v Näissä on niin paljon logiikkaa, että kaipaavat selitteen

2022-04-11 09:17 UTC, merged