VIITE-2717
finnishtransportagency/viite pull request #1198
Opened 2022-04-06 09:13 UTC by SitowiseValtteriV

Changed MassQuery ordering to ensure table is populated during the execution of the query

Alternative solutions would require refactoring of existing MassQuery.withIds uses. This solution works with the existing methods using MassQuery and doesn't cause issues in situations where multiple MassQuery calls are made within a single transaction block.

2022-04-06 11:41 UTC, LauriLitmanenSW commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/postgis/MassQuery.scala
>            val ret = f("temp_id")
vosiko ret nimetä esimerkiksi queryString?

2022-04-06 12:13 UTC, LauriLitmanenSW approved these changes
ret ja f muuttujat voisi nimetä uudestaan, muuten näyttäisi olevan OK

2022-04-06 12:43 UTC, marjukka-kokkonen-sitowise requested changes

2022-04-06 12:43 UTC, marjukka-kokkonen-sitowise commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/postgis/MassQuery.scala
> +          sqlu"TRUNCATE TABLE TEMP_ID".execute
Tähän kannattanee lisätä kommentti, joka kertoo, miksi tää trunc on tässä alussa, eikä tuolla lopussa, mikä noin äkkiseltään kuulostaisi oikeammalta.

2022-04-06 13:09 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/postgis/MassQuery.scala
>            val ret = f("temp_id")
toi ret ei kyl taida olla query string ja f  hof hommissa taitaa olla ihan normaali tapa ilmaista asia funktionaalisessa kielessä

2022-04-08 06:41 UTC, marjukka-kokkonen-sitowise approved these changes

2022-04-08 08:17 UTC, merged