VIITE-2869 convert road address browser target "Roads" to "Tracks"
finnishtransportagency/viite pull request #1297
Opened 2022-10-06 11:33 UTC by LauriLitmanenSW

added administrative class to class TrackForRoadAddressBrowser

2022-10-07 06:14 UTC, marjukka-kokkonen-sitowise requested changes

2022-10-10 05:47 UTC, LauriLitmanenSW commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala
> +      val dateCondition = "AND start_date <='" + startDate.get + "'"
On tarkistettu bäkkärin puolella

2022-10-10 09:31 UTC, SitowiseValtteriV commented on digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
> +  def roadAddressBrowserRoadPartsToApi(track: RoadPartForRoadAddressBrowser): Map[String, Any] = {
Tässä pitäisi varmaan olla ennemmin roadpart tms

2022-10-10 10:11 UTC, SitowiseValtteriV approved these changes

2022-10-10 10:22 UTC, merged