VIITE-2883 added a validation to notify user if Discontinuity code wa…
finnishtransportagency/viite pull request #1332
Opened 2022-11-07 13:44 UTC by SitowiseValtteriV

…s not applied while adding links

2022-11-07 13:54 UTC, SitowiseValtteriV commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
> +  def validateProjectAfterAddingLinks(projectId: Long, roadNumber: Long, roadPartNumber: Long, discontinuity: Discontinuity, newSession: Boolean = true): Seq[projectValidator.ValidationErrorDetails]
Metodin nimi saattaa implikoida turhan paljon, että tehtäisiin koko validointi

2022-11-08 06:20 UTC, LauriLitmanenSW commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
> +
Tarviiko nää molemmat funktiot ton withDynSession vai riittäskö että jommassakummassa on tämä if else (uuden session aloitus tai vanhan käyttö)

eli joko validaProjectAfterAddingLinks() tai validateProjectByIdHighPriorityOnly()

2022-11-08 07:52 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
> +  val DiscontinuityNotAddedToNewLinkMessage = s"Linkkejä lisätessä ei voitu päätellä viimeistä linkkiä, jolle antaa käyttäjän syöttämä jatkuvuuskoodi. Tarkista jatkuvuuskoodit."
harkittavaksi:
val UndeterminedLastNewLinkNoDiscontinuitySet

2022-11-08 07:52 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
> +    val projectLinksOnRoadPart = projectLinks.filter(pl => pl.roadNumber == roadNumber && pl.roadPartNumber == roadPartNumber)
(...kunhan mietin Viiteen sielunelämää... 
Apuah, eiks toi projectLinkDAO.fetchProjectLinksByProjectRoadPart palauta pelkkää haluttua tieosaa, kun tarttee vielä erikseen filtteröinnin..? Vai mitä mä en vaihteeks tajua...)

2022-11-08 07:52 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
> +      error(projectId, ValidationErrorList.DiscontinuityNotAddedToNewLink)(projectLinksOnRoadPart).toSeq
Sanoitkin jo, että tää on vähän sellanen BestEffort-ratkaisu.
Jep. Katsotaan keksitäänkö parempi ajatus.
Ensimmäinen ajatus: Voisiko validoinnin karsia koskemaan vain juuri kyseisessä Uusi-toimenpiteessä muodotettavia linkkejä?

2022-11-08 07:52 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
> +  def validateDiscontinuityAdded(projectId: Long, roadNumber: Long, roadPartNumber: Long, discontinuity: Discontinuity) : Seq[ValidationErrorDetails] = {
Nimeämis-nillinnii: Ymmärtäisin paremmin esim.:
def validateDiscontinuityIaAdded
tai
def validateDiscontinuityAvailability
tms.

2022-11-08 07:52 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
> +
...hmm?
validateDiscontinuityAdded -funktion sessiot uppoavat tän validateProjectAfterAddingLinks-funktion dynSessionien sisään.
Jos tuota validateProjectAfterAddingLinks joskus kutsutaan muualtakin, sitten sekin saattaa tarvita oman if(newSession)-blokkinsa.
Tätäkö tarkoitit?

2022-11-08 07:52 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
> +  def validateProjectAfterAddingLinks(projectId: Long, roadNumber: Long, roadPartNumber: Long, discontinuity: Discontinuity, newSession: Boolean = true): Seq[projectValidator.ValidationErrorDetails]
Komppaan - kun se tekee vain high prio-validoinnit.
Sit mietin muutenkin tuota nimeä - mieluummin sellaisia nimiä, jotka kertovat mitä funkkari tekee, kuin milloin sitä käytetään - vaikka tässä tapauksessa ymmärrän kyllä tuon.
Mut parempi nimi olis.... öööhhh....
Emmätiä. validateProjectForHighPriorityAndDiscontinuity?

2022-11-08 14:25 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
> +  val DiscontinuityNotAddedToNewLinkMessage = s"Linkkejä lisätessä ei voitu päätellä viimeistä linkkiä, jolle antaa käyttäjän syöttämä jatkuvuuskoodi. Tarkista jatkuvuuskoodit."
Öh...
UndeterminedLastNewLinkDiscontinuityNotSet

2022-11-08 14:32 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
> +      error(projectId, ValidationErrorList.DiscontinuityNotAddedToNewLink)(projectLinksOnRoadPart).toSeq
(obsolete, refaktoroitiin toisin)

2022-11-08 14:33 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
> +  def validateDiscontinuityAdded(projectId: Long, roadNumber: Long, roadPartNumber: Long, discontinuity: Discontinuity) : Seq[ValidationErrorDetails] = {
(obsolete, refaktoroitiin toisin)

2022-11-08 14:34 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
> +  def validateProjectAfterAddingLinks(projectId: Long, roadNumber: Long, roadPartNumber: Long, discontinuity: Discontinuity, newSession: Boolean = true): Seq[projectValidator.ValidationErrorDetails]
(obsolete, refaktoroitiin toisin)

2022-11-08 14:34 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
> +    val projectLinksOnRoadPart = projectLinks.filter(pl => pl.roadNumber == roadNumber && pl.roadPartNumber == roadPartNumber)
(obsolete, refaktoroitiin toisin)

2022-11-09 06:51 UTC, LauriLitmanenSW approved these changes

2022-11-09 09:06 UTC, LauriLitmanenSW requested changes

2022-11-09 09:06 UTC, LauriLitmanenSW commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
> +                val errorAddingDiscontinuity = if (!projectLinks.exists(_.discontinuity == discontinuity)) Some(UndeterminedLastNewLinkNoDiscontinuitySet) else None
discontinuity parametrin voisi nimetä userGivenDiscontinuity tms kertomaan sen että tämä on se käyttäjän ilmoittama jatkuu koodi joka halutaan viimeiselle projektilinkille

2022-11-09 09:20 UTC, LauriLitmanenSW approved these changes

2022-11-11 21:54 UTC, marjukka-kokkonen-sitowise approved these changes

2022-11-14 10:38 UTC, merged