VIITE-2770 Removed vvh and oag usages.
finnishtransportagency/viite pull request #1354
Opened 2022-11-25 14:31 UTC by ao-sitowise

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise reviewed
automaagirivitys-nillinniitä iso kasa.
Mut koodi siistiytyyyyy <3

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
> +class ProjectService(
(Nääätttiiii! <3 :) )

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala
> +  val projectService: ProjectService = new ProjectService(roadAddressService, mockRoadLinkService, nodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, projectLinkDAO
Sama tänne: 
nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectLinkNameDAOSpec.scala
> +  val projectService = new ProjectService(roadAddressServiceRealRoadwayAddressMapper, mockRoadLinkService, mockNodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, pr
Ja tänne:
nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
> +  val projectService: ProjectService = new ProjectService(roadAddressServiceRealRoadwayAddressMapper, mockRoadLinkService, mockNodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO
...ja tänne:
nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
> +  val projectServiceWithRoadAddressMock: ProjectService = new ProjectService(mockRoadAddressService, mockRoadLinkService, mockNodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO,
...ja tänne:
nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
> +  val projectService = new ProjectService(roadAddressService, mockRoadLinkService, mockNodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, projectLinkDAO, nodeDAO, n
... nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
> +  val projectServiceWithRoadAddressMock = new ProjectService(mockRoadAddressService, mockRoadLinkService, mockNodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, pro
... nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
> +  val projectService: ProjectService = new ProjectService(mockRoadAddressService, mockRoadLinkService, mockNodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, projec
... nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilderSpec.scala
> +  val projectService = new ProjectService(roadAddressService, mockRoadLinkService, mockNodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, projectLinkDAO, nodeDAO, n
... nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
> +  val projectService = new ProjectService(roadAddressService, mockRoadLinkService, nodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, projectLinkDAO, nodeDAO, nodeP
... nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/integration/Viite_13_218_spec.scala
> +  val projectService_db: ProjectService = new ProjectService(roadAddressService_db, mockRoadLinkService, nodesAndJunctionsService_db, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, proje
... nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala
> +  val projectService: ProjectService = new ProjectService(roadAddressService, mockRoadLinkService, mockNodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, projectLin
... nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala
> +  val projectService: ProjectService = new ProjectService(roadAddressService, mockRoadLinkService, mockNodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, projectLin
... nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala
> +  val projectService = new ProjectService(roadAddressService, mockRoadLinkService, mockNodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, projectLinkDAO, nodeDAO, n
... nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 13:28 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala
> +  val projectServiceWithRoadAddressMock = new ProjectService(mockRoadAddressService, mockRoadLinkService, mockNodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, pro
... nil: Älä hyväksy automaagin pitkiä rivejä

2022-11-28 15:30 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/ChangeType.scala
> +  def affects(id: String, assetTimeStamp: Long): Boolean = {
Tiekamussa ei ole muutos tietoja. Varmaan ton change homman vois poistaa. Voi tietty säilyttää referenssinä.

2022-12-16 13:32 UTC, SitowiseValtteriV requested changes
kaksi indentointia näytti puuttuvan vielä

2022-12-16 13:32 UTC, SitowiseValtteriV commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectLinkNameDAOSpec.scala
> +  val projectService = new ProjectService(roadAddressServiceRealRoadwayAddressMapper, mockRoadLinkService, mockNodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, pr
Tämä oli jäänyt vielä indentoimatta

2022-12-16 13:32 UTC, SitowiseValtteriV commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
> +  val projectService = new ProjectService(roadAddressService, mockRoadLinkService, nodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, projectLinkDAO, nodeDAO, nodeP
Tämä myös

2022-12-19 10:08 UTC, SitowiseValtteriV approved these changes

2022-12-19 10:15 UTC, merged