VIITE-2879 Calc error message changes
finnishtransportagency/viite pull request #1367
Opened 2022-12-09 14:11 UTC by ao-sitowise

2022-12-14 11:11 UTC, LauriLitmanenSW commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
> +  val ContinuosAddressCapErrorMessage = UnsuccessfulRecalculationMessage + " Tieosoiteet ei muodostu jatkuvaksi."
Kirjoitusvirhe p.o. "Tieosoitteet eivät muodostu jatkuvaksi."

2022-12-14 11:22 UTC, LauriLitmanenSW commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
> +  val LengthMismatchErrorMessage = UnsuccessfulRecalculationMessage + " Linkin %s uusi pituus poikkeaa vanhasta."
Kuvaavampi viesti ja ohje käyttäjälle kuinka toimia

val ContactViiteSupportMessage = "Ota yhteys Viite tukeen."

val LengthMismatchErrorMessage = UnsuccesfulRecalculationMessage + " Linkin uusi pituus eroaa yli sallitun rajan (%maxDiffForChange) vanhaan pituuteen verrattuna. " + ContactViiteSupportMessage

2022-12-14 13:17 UTC, SitowiseValtteriV commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
> +  val ContinuosAddressCapErrorMessage = UnsuccessfulRecalculationMessage + " Tieosoiteet ei muodostu jatkuvaksi."
myös ContinuosAddressCapErrorMessage => ContinuousAddressCapErrorMessage

2022-12-16 13:43 UTC, SitowiseValtteriV requested changes

2022-12-16 13:43 UTC, SitowiseValtteriV commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
> +  val LengthMismatchErrorMessage       = UnsuccessfulRecalculationMessage + " Linkin %s uusi pituus eroaa yli sallitun rajan (%d) vanhaan pituuteen verrattuna." + ContactViiteSupportMessage
Eikös näissä nyt tule "Ota yhteys Viite tukeen." kahdesti?
```
val UnsuccessfulRecalculationMessage = "Etäisyysarvojen laskenta epäonnistui." + ContactViiteSupportMessage 
val ContinuousAddressCapErrorMessage = UnsuccessfulRecalculationMessage + " Tieosoitteet eivät muodostu jatkuvaksi." + ContactViiteSupportMessage
=> val ContinuousAddressCapErrorMessage = "Etäisyysarvojen laskenta epäonnistui." + ContactViiteSupportMessage + " Tieosoitteet eivät muodostu jatkuvaksi." + ContactViiteSupportMessage
```

2022-12-16 13:53 UTC, SitowiseValtteriV commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
>    val UnsuccessfulRecalculationMessage = "Etäisyysarvojen laskenta epäonnistui."
UnsuccessfulRecalculationMessage palautuu käyttäjille joissain tapauksissa, pitäisikö refaktoroida niihin virheilmoituksiin joko kuvaavampi virhe tai sitten lisätä vielä vakio, jossa on myös mukana ContactViiteSupportMessage.

2022-12-19 06:18 UTC, LauriLitmanenSW approved these changes

2022-12-19 07:58 UTC, merged