Viite 1576
finnishtransportagency/viite pull request #1377
Opened 2023-01-02 13:48 UTC by ao-sitowise

2023-01-03 08:05 UTC, SitowiseValtteriV commented on viite-UI/src/view/ProjectEditForm.js
> +                  $('.form,.form-horizontal,.form-dark').append('<label class="validation-warning">' + response.validationErrors[0].errorMessage + '<br>' + "LinkId: " + response.validationErrors[0].i
"response.validationErrors[0]" onko varoitus aina järjestyksessä ensimmäinen?

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise requested changes
ProjectValidatorSpec.scala:sta tarttee ottaa automaattirivitykset pois. 
Nyt se on ihan kamala pitkine riveineen.
Ei jääny mitään tolkkua siitä, oliko siellä nyt jotain "oikeitakin" muutoksia.

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise commented on viite-UI/src/view/ProjectEditForm.js
> +              if (response.validationErrors.filter(error => error.errorCode === 38).length > 0) {
nil: "error.errorCode === 38"
Magic number -> muuttuja

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
> +  val roadwayAddressMapper                           = new RoadwayAddressMapper(roadwayDAO, linearLocationDAO)
😍

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
> +  val projectService: ProjectService = new ProjectService(mockRoadAddressService, mockRoadLinkService, mockNodesAndJunctionsService, roadwayDAO, roadwayPointDAO, linearLocationDAO, projectDAO, projec
Mur! Rivitys takas!

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
> +                         ): ProjectLink = {
😍

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
> +        Roadway(raId + 2, roadwayNumber3, 19999L, 1L, AdministrativeClass.State, Track.LeftSide, Discontinuity.EndOfRoad, 10L, 20L, reversed = false, DateTime.now(), None, "test_user ", None, 8, NoTe
Eijjeijjei, nyt linkittyy //LeftSide-kommentti väärään koodiin

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
> +      val ra        = Seq( //Combined
Eijjeijjei, nyt linkittyvät kommentit vääriin riveihin!
Formatointi takas!

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
> +      val projectLinks   = Seq(ProjectLink(1001, roadNumber, roadPartNumber, Combined, Continuous, 0, 0, 0, 0, None, None, Some(user), 5175001.toString, 0.0, 72.789, SideCode.Unknown, (NoCP, NoCP), (
Eikä yhdistetä one-lineriksi tätäkään.
Tää on nyt vaan kertakaikkiaan kamala.

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
> +      val projectLinks   = Seq(ProjectLink(1001, roadNumber, roadPartNumber, Combined, Continuous, 0, 0, 0, 0, None, None, Some(user), 5175001.toString, 0.0, 72.789, SideCode.Unknown, (NoCP, NoCP), (
Ja tänne sama:
Eikä yhdistetä one-lineriksi tätäkään.
Tää on nyt vaan kertakaikkiaan kamala.

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
> +      val projectLinks   = Seq(ProjectLink(1001, roadNumber, roadPartNumber, Combined, Continuous, 0, 0, 0, 0, None, None, Some(user), 5175001.toString, 0.0, 72.789, SideCode.Unknown, (NoCP, NoCP), (
...ja tänne...

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
> +      val projectLinks   = Seq(ProjectLink(1000, roadNumber, roadPartNumber, Combined, Continuous, 0, 0, 0, 0, None, None, Some(user), 5174997.toString, 0.0, 152.337, SideCode.Unknown, (NoCP, NoCP),
...ja tänne...

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
> +      val projectLinks   = Seq(ProjectLink(1007, roadNumber, roadPartNumber, Combined, Continuous, 0, 0, 0, 0, None, None, Some(user), 5174936.toString, 0.0, 117.582, SideCode.Unknown, (NoCP, NoCP),
...ja...

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
> +      val roadAddresses    = Seq(RoadAddress(12345, linearLocationId, 19999L, 1L, AdministrativeClass.State, Track.Combined, Discontinuity.MinorDiscontinuity, 0, 10, Some(DateTime.parse("1901-01-01")
...ja tänne, rivitys takas!

2023-01-11 14:17 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
> +      val roadAddresses    = Seq(RoadAddress(12345, linearLocationId, 19999L, 1L, AdministrativeClass.State, Track.Combined, Discontinuity.Continuous, 0, 10, Some(DateTime.parse("1901-01-01")), None,
Joo ei, täältä tarttee ottaa 90% automaattiformatoinneista pois.
Nää ei auta, nää tekevät koodista entistä hankalalukuisempaa.

2023-01-12 08:42 UTC, SitowiseValtteriV approved these changes

2023-02-14 13:18 UTC, merged