Viite-2014 Validate single AdminClass on link
finnishtransportagency/viite pull request #1380
Opened 2023-01-04 13:38 UTC by ao-sitowise

2023-01-12 06:58 UTC, marjukka-kokkonen-sitowise requested changes
Uudelleennimeämispyyntö. 
SingleAdminClassOnLink -> UniformAdminClassOnLink
tai joku muu vastaava; "single" piuhoittaa ajatuksia väärin.

Muuten näyttää hyvältä.
Ja nyt testi (jo muutamissa aiemmissakin pullareissa) on luettavan oloinen ja kokoinen, kun bulkki on muualla \o/

2023-01-12 06:58 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
> +    val reversedProjectLinks = allProjectLinks.groupBy(_.linkId).filter(_._2.size > 1)
En ymmärrä nimeä - miksi "reversed---"?
Tää näyttäis olevan paremminkin multiLinearLocationProjectLinksLinks tai jotain?
Vai pitäisikö sisään tulevan allProjectLinksin olla aina käännetty, eli _sen_ nimi vaatis fiksin?

2023-01-12 06:58 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
> +        Seq(error(project.id, ValidationErrorList.SingleAdminClassOnLink)(pls).get)
(Alkuperäinen kommentti:
Tänne mennään, vaikka useammallakin kuin yhdellä linkillä olis joku muu adminClass.
-> funktion nimi checkSingleAdminClassOnLink ei kuulosta nyt oikealta.)

Edit: Uudelleennimeämispyyntö: ValidationErrorList.SingleAdminClassOnLink nimeämiseen muutos funktiota vastaavasti.

2023-01-12 06:58 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
> +  def checkSingleAdminClassOnLink(project: Project, allProjectLinks: Seq[ProjectLink]): Seq[ValidationErrorDetails] = {
Nyt luettaessa tulkkautuu (myös) muotoon "tarkista yksittäinen linkin adminclass".
-> Uudelleennimeämispyyntö, esim.
checkUniformAdminClassOnLink

2023-01-12 06:58 UTC, marjukka-kokkonen-sitowise commented on digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
> +  val SingleAdminClassOnLinkMessage = "Linkki voi sisältää vain yhtä hallinnollista luokkaa."
Tänne toi sama uudelleennimeämispyyntö
(eli esim. Single -> Uniform)

2023-02-16 09:07 UTC, LauriLitmanenSW approved these changes

2023-02-17 16:16 UTC, merged