VIITE-2933 numbering status available only if no other status is set …
finnishtransportagency/viite pull request #1392
Opened 2023-01-13 12:02 UTC by ao-sitowise

…to the roadpart.

2023-01-16 07:55 UTC, LauriLitmanenSW commented on viite-UI/src/view/ProjectEditForm.js
> +        projectCollection.getProjectLinks().then(function (pls) {
Eikös tässä voisi käyttää projectCollection.fetchedProjectLinks sen sijaan että haetaan projektilinkit uudestaan?

2023-01-16 08:02 UTC, ao-sitowise commented on viite-UI/src/view/ProjectEditForm.js
> +        projectCollection.getProjectLinks().then(function (pls) {
Ne tais olla eri tyyppisiä niin että en löytänyt alkuperäistä tie/osaa niistä.

2023-01-16 10:28 UTC, LauriLitmanenSW requested changes
Ylimääräinen fetchi hidastaa formin esittämisen käyttäjälle.  Tähän voisi kehittää jonkun ratkaisun, esim että projektilinkeistä ollaan aina ajantasalla projectCollectionissa (jos ei jo olla), jolloin tälläistä fetchiä ei tarvita tässä välissä.

2023-01-17 06:53 UTC, LauriLitmanenSW commented
Mikä tuon roadaddressRoadNumberin idea on? Onko se projektissa annettava tienumero? Jos on niin voisko sen nimetä newRoadNumber ja newRoadPart tai joksikin kuvaavammaksi? Nyt projectAddressLink (joka on myös huono nimeäminen) on kaksi roadNumber ja roadPartNumberia ja seuraavaan koodaajan on vaikea selvittää mitä eroa näillä kahdella on.

2023-01-17 13:02 UTC, ao-sitowise commented
> Mikä tuon roadaddressRoadNumberin idea on? Onko se projektissa annettava tienumero? Jos on niin voisko sen nimetä newRoadNumber ja newRoadPart tai joksikin kuvaavammaksi? Nyt projectAddressLink (joka on myös huono nimeäminen) on kaksi roadNumber ja roadPartNumberia ja seuraavaan koodaajan on vaikea selvittää mitä eroa näillä kahdella on.

RoadaddressRoadNumber tulee projektilinkiltä. Se on roadwaylla eli alkuperäinen tienumero. Juuri siihen verrataan ettei ole jollain toimenpiteellä tienumeroa jo muutettu. Tossa se on otettu mukaan projektilinkiltä ui:lle.

2023-01-17 13:04 UTC, LauriLitmanenSW commented
Olisiko parempi nimi sitten originalRoadNumber ja originalRoadPartNumber?

2023-01-18 14:21 UTC, ao-sitowise commented
> 

Siinä täytyisi sitten muuta vastaavat refaktoroida samalla tavalla.

2023-02-16 09:02 UTC, LauriLitmanenSW approved these changes

2023-02-17 11:38 UTC, merged