VIITE-2922 Change UI project list loading with ely.
finnishtransportagency/viite pull request #1417
Opened 2023-02-03 08:49 UTC by ao-sitowise

2023-02-09 10:32 UTC, LauriLitmanenSW commented on viite-UI/src/view/navigationpanel/ProjectListModel.js
> -        var html = '<table style="table-layout: fixed; width: 100%;">';
Chatissa käytykin jo keskustelua tästä mutta lisätään tännekin: 

html stringin rakentaminen luupissa konkatenaation avulla on nopeampaa kuin tuo appendin käyttö.

Eli tätä alkuperäistä voisi muokata sen verran että nuo inline tyylit siirretään tyyli tiedostoihin mutta pidetään tämä konkatenaatio tapa tuon html tablen rakentamisena ja luupin jälkeen tehdään tuosta massiivisesta stringistä sitten html elementti joka lisätään DOM puuhun.

2023-02-09 10:33 UTC, LauriLitmanenSW commented on viite-UI/src/view/navigationpanel/ProjectListModel.js
> -        var html = '<table style="table-layout: fixed; width: 100%;">';
Muutetaan myös 
var muuttujat joko const tai let

2023-02-09 11:21 UTC, LauriLitmanenSW requested changes
pari kommenttia

2023-02-09 12:05 UTC, LauriLitmanenSW commented on viite-UI/src/view/navigationpanel/ProjectListModel.js
>                  html += '<td id="innerOpenProjectButton"><button class="project-open btn btn-new" style="alignment: right; margin-bottom: 6px; margin-left: 50px" id="open-project-' + proj.id + '" val
indentaatio vielä vähän vinksin vonksin

2023-02-15 12:40 UTC, marjukka-kokkonen-sitowise commented on digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
> +  get("/roadlinks/roadaddress/project/states/:projectIDs", operation(getRoadAddressProjectStates)) {
Etsäviitsis vielä korjata ton mun typokommentin tosta.. 
"(<i>projectIDs</i>)"

2023-02-15 12:41 UTC, LauriLitmanenSW approved these changes

2023-02-17 12:11 UTC, merged