VIITE-3046 RoadaddressChangesBrowser to include end date in the listing
finnishtransportagency/viite pull request #1526
Opened 2023-07-21 09:18 UTC by mvrkus-sitowise

Browser end-date changed to add 1 day to the end-date input, so that listing shows projects from the date selected as the listing's end-date.

2023-07-28 09:44 UTC, LauriLitmanenSW approved these changes

2023-07-31 07:59 UTC, marjukka-kokkonen-sitowise approved these changes

2023-07-31 08:00 UTC, marjukka-kokkonen-sitowise requested changes
Eipäs ku!

2023-07-31 08:02 UTC, marjukka-kokkonen-sitowise approved these changes
Eiku ei mitään... 😅

2023-07-31 08:47 UTC, merged