VIITE-3055 nodes and junctions interface
finnishtransportagency/viite pull request #1547
Opened 2023-11-03 14:21 UTC by mvrkus-sitowise

VIITE-3055

Rajapinta solmuille ja liittymille

2023-11-09 09:38 UTC, LauriLitmanenSW commented on viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
> +            throw t
throw t kannattaa ottaa pois tästä, tuolla handleCommonIntegrationAPIExceptions funktiossa on sitten uudelleen heitto jos exception ei ole fataali

2023-11-09 09:52 UTC, LauriLitmanenSW commented on viite-backend/api/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
> +          }
indentaatio fixi

2023-11-09 10:55 UTC, LauriLitmanenSW commented on viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/LinearLocationDAO.scala
> +                                      validFrom: DateTime, validTo: Option[DateTime], createdBy: String, createdTime: Option[DateTime], llId: Seq[Long])
Hmm.. Pitäisikö näiden olla mielummin JunctionDAO:ssa? 
Ja samoin noiden alla olevien get -funktioiden.

2023-11-09 12:19 UTC, LauriLitmanen commented on viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/LinearLocationDAOSpec.scala
> +  test("Test FetchCoordinatesForJunction when there are 2 linear locations with the same start and endpoints, but is against digitizing Then return coordinate point of junction") {
Testin nimeä vois selkeyttää vähän 🤔

2023-11-09 12:19 UTC, LauriLitmanen commented on viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/LinearLocationDAOSpec.scala
> +      val expectedPoint: Option[Point] = Some(Point(0.0, 200.0))
Tähän kommentti miksi tuo on expectedPoint

2023-11-09 12:20 UTC, LauriLitmanen commented on viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/LinearLocationDAO.scala
> +                                      validFrom: DateTime, validTo: Option[DateTime], createdBy: String, createdTime: Option[DateTime], llId: Seq[Long])
eli kaikki jotka ovat enemmän liittymään pohjautuvia voisi siirtää tuonne junctionDAO:on

2023-11-09 12:29 UTC, LauriLitmanenSW commented on viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/LinearLocationDAO.scala
> +                                      validFrom: DateTime, validTo: Option[DateTime], createdBy: String, createdTime: Option[DateTime], llId: Seq[Long])
eli kaikki jotka ovat enemmän liittymään pohjautuvia voisi siirtää tuonne junctionDAO:on

2023-11-09 12:30 UTC, LauriLitmanenSW commented on viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/NodesAndJunctionsServiceSpec.scala
> +  test("Test getAllValidNodesWithJunctions When valid nodes and junctions exist Then return valid nodes with only junctions") {
Pitäiskö tässä lukea "Then return only valid nodes with junctions"

2023-11-09 12:31 UTC, LauriLitmanenSW commented on viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/LinearLocationDAOSpec.scala
> +  test("Test FetchCoordinatesForJunction when there are 2 linear locations with the same start and endpoints, but is against digitizing Then return coordinate point of junction") {
Selkeämpi nimi tälle testille

2023-11-09 12:31 UTC, LauriLitmanenSW commented on viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/LinearLocationDAOSpec.scala
> +      result should be(expectedPoint)
Kommentti miksi tuo on expectedEndPoint

2023-11-09 12:31 UTC, LauriLitmanenSW requested changes
Pari kommenttia

2023-11-27 08:48 UTC, mvrkus-sitowise commented on viite-backend/api/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
> +
pois

2023-11-27 08:49 UTC, mvrkus-sitowise commented on viite-backend/api/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
> +
rivi pois

2023-11-27 11:47 UTC, marjukka-kokkonen-sitowise reviewed
(...nii, kannattais vissii lähettääkki nää kommentit... :) )

2023-11-30 12:55 UTC, marjukka-kokkonen-sitowise approved these changes
Mun puolesta ei muuta, hyvältä näyttää! 👌

2023-11-30 13:26 UTC, LauriLitmanenSW approved these changes

2023-12-04 08:45 UTC, merged