Viite 3097 road address changes browser modification
finnishtransportagency/viite pull request #1564
Opened 2024-02-09 12:58 UTC by jounijoh

Updated fetchChangeInfosForRoadAddressChangesBrowser to get all roadway changes that are linked to projects that fit the search filters. Replaced multiple if clauses with ListBuffer to make the dynamic SQL query construction more straightforward.  

In the constructed query RelevantProjects filters projects based on searched criteria and AllRelatedRoadwayChanges fetches all roadway changes  related to RelevantProjects.

Added a new unit test to check that the updated fetchChangeInfosForRoadAddressChangesBrowser correctly returns all related roadway changes linked to projects. The test checks that, when multiple projects affect the same road part which is searched, the method should return and all road way changes linked to the projects even out side the filtered criteria (road part number) and that the fetch returns correctly with the given date window.

2024-02-12 06:58 UTC, sasuolanderSito commented on viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAO.scala
> +      val conditions = scala.collection.mutable.ListBuffer[String]()
Hyvään tyylisessä scala koodissa ei kannata käyttää ListBuffer, jos ei ole joku erityinen syy.

Tää olis tyyli mielessä parempi:
val conditions:Seq[String] = Seq.empty[String]

2024-02-12 14:48 UTC, marjukka-kokkonen-sitowise requested changes
Request changes joo, mut siis, yleisesti näyttää tosi hyvältä! 👍

2024-02-12 14:48 UTC, marjukka-kokkonen-sitowise commented on viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
> +      val startDate1 = "2022-01-01"
startDateX on... ....käyttäjän syöttämä hakuparametri.
->termin niminillitys: 
p.o. queryStartDateX 
tai jotain vastaavaa?

(Mutta yleisesti: nimeäminen magic numberien sijaan oikein hyvä! 👍 💪 )

2024-02-12 14:48 UTC, marjukka-kokkonen-sitowise commented on viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
> +      runUpdateToDb(s""" insert into ROADWAY_CHANGES(project_id,change_type,new_road_number,new_road_part_number,old_discontinuity,new_discontinuity,
(Kunhan rutisen ku näen, mut ei tartte tehdä mitään (ei kuulu tiketin skooppiin)..:
... ja tätä ei löydy funktiona, vaan tarttee kirjoittaa erilleen, jep... 🤦 )

2024-02-12 14:49 UTC, marjukka-kokkonen-sitowise commented
Nii ja, sit ku mergen aika...
Toi pullarikommentti olis hyvä mergecommitissa! Sille vaan ekaks vielä joko yksrivinen tiivistelmä ihan ekaks lauseeks/kappaleeks, tyyliin
"VIITE-3097 Road address changes browser now returns whole project data for every matching criteria" tai jotain, niin näkee sit ekana kontekstin.

2024-02-13 07:19 UTC, jounijoh commented on viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAO.scala
> +      val conditions = scala.collection.mutable.ListBuffer[String]()
Okei ei mulla sille sen syvällisempää syyytä, vaikutti omaan silmään yksinkertaisemmalta. Mutta voin toki vaihtaa sen,    kun Seq tosiaan käytössä laajemmin ja todettu toimivaksi.

2024-02-13 07:24 UTC, sasuolanderSito commented on viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAO.scala
> +      val conditions = scala.collection.mutable.ListBuffer[String]()
karkea heitti, 90% tilanteissa Seq ja ListBuffer ei ole mitään eroa.
Jos pitää päivittää listaa jossa on useita miljonia kohteita, silloin ListBuffer oikea ratkaisu. 
Seq on muuttumaton lista tyyppi, joten joka kerta pitää tehdä kopio koko listasta ja uusien/muuttuneiden osien kanssa.

2024-02-13 09:11 UTC, jounijoh commented on viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
> +      runUpdateToDb(s""" insert into ROADWAY_CHANGES(project_id,change_type,new_road_number,new_road_part_number,old_discontinuity,new_discontinuity,
Kieltämättä helpottaisi elämää ja luettavuutta. jos toi olisi erillisenä funktiona, kun aika monessa paikkaa käytössä

2024-02-13 13:42 UTC, marjukka-kokkonen-sitowise commented on viite-backend/viite-main/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
> +      runUpdateToDb(s""" insert into ROADWAY_CHANGES(project_id,change_type,new_road_number,new_road_part_number,old_discontinuity,new_discontinuity,
(...sinänsä, jos refaktorointi hotsittaa / tuntuis järkevältä, niin en mä ainakaan käy kieltämästä tuon funktioittamista. :) )
(Onks se sit sama tiketti vai eri tiketti vai pullari ilman tikettiä, en ota kantaa)

2024-02-13 14:11 UTC, marjukka-kokkonen-sitowise approved these changes
👌

2024-02-14 06:34 UTC, merged