Viite 3094 add scalike jdbc
finnishtransportagency/viite pull request #1680
Opened 2024-09-13 15:03 UTC by jounijoh

1. Set up ScalikeJDBC configuration and database connection
2. Refactored Road Name models into separate files
3. Added new Roadway case class to be used in fi.vaylavirasto.viite package
4. Implemented initial DAO methods for Road Name data access with ScalikeJDBC

2024-09-16 13:49 UTC, marjukka-kokkonen-sitowise commented on project/build.scala
> +
<3

2024-09-16 13:50 UTC, marjukka-kokkonen-sitowise commented on project/build.scala
> +  val ScalikeJdbcJodaTimeVersion = "3.4.2" // Should match your ScalikeJdbcVersion
Hmm, tähän 
val ScalikeJdbcJodaTimeVersion = ScalikeJdbcVersion
?

2024-09-16 13:52 UTC, marjukka-kokkonen-sitowise commented on project/build.scala
> +        httpCore,
alla on apacheHttp, nää ovat toistoa

2024-09-16 15:02 UTC, marjukka-kokkonen-sitowise requested changes

2024-09-16 15:02 UTC, marjukka-kokkonen-sitowise commented on viite-backend/database/src/main/scala/fi/vaylavirasto/viite/postgis/PostGISDatabaseScalikeJDBC.scala
> +        maxSize = 7,
Tääällä ja tuolla env.propertiesissa on nyt molemmissa arvot. env.propertiesit kommentteihin jos käytössä fiksatut

2024-09-16 15:02 UTC, marjukka-kokkonen-sitowise commented on viite-backend/conf/env.properties
> +scalikejdbc.pool.initialSize=5
Tääällä ja tuolla PostGISDatabaseScalikeJDBC:ssa on nyt molemmissa arvot. nämä kommentteihin jos käytössä on fiksatut?

2024-09-19 11:01 UTC, jounijoh commented on viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/RoadNameScalikeDAO.scala
> +    id = rs.long("id"),
Oiskohan tähän joku plugin olemassa, jotta saisi pikanäppäin yhdistelmällä fromatoitua noin 🤔

2024-09-20 11:51 UTC, marjukka-kokkonen-sitowise commented on viite-backend/conf/env.properties
> +scalikejdbc.jdbc.url=jdbc:postgresql://localhost:5432/viite
Jaa, ilmeisesti ainakin Idea osaa jyrätä nämä komentorivi/konfiguraatioparametreilla, et ehkä tää ei ookaan ongelma.

2024-10-04 06:03 UTC, marjukka-kokkonen-sitowise approved these changes

2024-10-04 06:59 UTC, marjukka-kokkonen-sitowise commented on viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/RoadNameScalikeDAO.scala
> +   * @param endDate   Optional end date for the road names
Heeetkone, voiko startDatekin olla null?!?
Eeeei kyl pitäis olla koskaan.
endDate varmaan on null, jos nimi on vielä voimassa.

2024-10-04 07:05 UTC, marjukka-kokkonen-sitowise commented on viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/RoadNameScalikeDAO.scala
> +   * @param endDate   Optional end date for the road names
Eiku siis. Otetaas takas. Kommenttieja tarttee säätää.
Jotain tähän tyyliin:

   * @param startDate Optional oldest date from where the road names are returned
   * @param endDate   Optional latest date from where the road names are returned

Mut en oo tohonkaan tyytyväinen, mielellään vielä paremmin/selkeämmin 😅 
Nyt noista kommenteista saa sellaisen käsityksen, että niillä rajataan tulokset just tasan noihin päiviin.

2024-10-04 07:06 UTC, marjukka-kokkonen-sitowise commented on viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/RoadNameScalikeDAO.scala
> +   * @param endDate   Optional end date for the road names
Ja tänne toi sama ku yllä

2024-10-25 12:41 UTC, closed without merging