Viite 3094/viite 3215 migrate remaning files in database module
finnishtransportagency/viite pull request #1724
Opened 2024-12-17 08:32 UTC by jounijoh

- Modified PingAPI and -DAO to use ScalikeJDBC, added test to test the ping
- Modified ComplementaryLinkDAO, MunicipalityDAO, LinkDAO, ProjectLinkNameDAO and their Spec files to use ScalikeJDBC
- Modified getUser in PostGISUserProvider to return Option as it should
- Modified PostGISUserProviderSpec to use ScalikeJDBC
- RoadLinkService and -Spec to use ScalikeJDBC and removed all methods without use

BaseDAO: 
- Added Select method to return first result
- Added implicit val dateTimeMapper

2024-12-17 09:23 UTC, marjukka-kokkonen-sitowise commented on viite-backend/database/src/main/scala/fi/vaylavirasto/viite/dao/PingDAO.scala
> +  def getDbTime(implicit session: DBSession): String = {
Kauniisti tehty funktio kommentteineen!

2024-12-17 09:30 UTC, marjukka-kokkonen-sitowise commented on viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
> +        ),
nil: sulun alignaus

2024-12-17 09:35 UTC, marjukka-kokkonen-sitowise commented on viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
> +            ORDER BY plh.ROAD_NUMBER, plh.ROAD_PART_NUMBER, plh.END_ADDR_M
nil: case

2024-12-17 09:35 UTC, marjukka-kokkonen-sitowise commented on viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
> +            ORDER BY plh.ROAD_NUMBER, plh.ROAD_PART_NUMBER, plh.END_ADDR_M
(ja näköjään tos alempana kans)

2024-12-17 09:38 UTC, marjukka-kokkonen-sitowise commented on viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
> +println(query)
(on vanhassakin - mutta tarvitaanko pprintln:iä?)

2024-12-17 09:40 UTC, marjukka-kokkonen-sitowise commented on viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
> +    /**
funktio siirtynyt välilyönnin tai  kaks oikealle - vahingossa?

2024-12-17 11:13 UTC, marjukka-kokkonen-sitowise reviewed
Siinäpä nuo, eipä tuonne varsinaisiin ScaLike -muutoksiin kommentoitavaa löytynyt, nillejä vain. :)

2024-12-19 10:12 UTC, LauriLitmanen requested changes
pari nilliä

2024-12-19 10:12 UTC, LauriLitmanen commented on viite-backend/viite-main/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
> +          Linear_Location ON (Linear_Location.id = Project_Link.Linear_Location_Id)
taulujen nimet on pienellä paitsi Linear_Location ja Project_Link. Pitäskö noikin laittaa pinellä?

2024-12-19 13:49 UTC, LauriLitmanen approved these changes

2024-12-23 08:45 UTC, merged